### ISSUE TITLE
Missing framework

### ISSUE THREAD

**Issue by pablopeu** [shark92651/LaserParamsConverter#1]
Hi, ran setup, was informed that framework was missing an was provided with the downloads page, downloaded x64, failed, then x32 and failed again, always same error message, restarted, problem repeats, can't run the app, are any other dependencies necessary? 
I'm running win10pro/64
Thanks
![image](https://user-images.githubusercontent.com/25783916/174664605-107cde8b-f514-4ea1-b08f-f6831ab5bbd3.png)

**Comment by pablopeu** [comment]
Solved it by installing: .NET 6.0 **Desktop** Runtime (v6.0.6) from this link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

**Comment by shark92651** [comment]
Glad you found a workaround. In my testing it always successfully downloaded and installed the runtime when I clicked "Yes"
