### ISSUE TITLE
Pulse Width - Changing it globally

### ISSUE THREAD

**Issue by ExR90** [shark92651/LaserParamsConverter#12]
Not directly related to switching Lens, but seems like a relevant feature: Mass changing pulse width on MOPA devices. The specific use case is when you get a file WITHOUT pulse width; the pulse width of 2ns is still hard-coded into the file even if you have a different pulse width set in your own default. This is typically found in scenarios with files created by people without a MOPA system and then you have a MOPA system and want to open that file and use it. This becomes very important on files with lots of pens - calibration files is one of them.

**Comment by shark92651** [comment]
I will add an option to set this. Look for it in next update
