### ISSUE TITLE
Ironically, you're violating your own license.

### ISSUE THREAD

**Issue by tatarize** [shark92651/LaserParamsConverter#2]
Releasing a file under GPL requires that, if you release the binaries you must release the source. You're releasing the binaries and not releasing the source.

**Comment by shark92651** [comment]
I must have picked the wrong license type then. My intention is to release the software as freeware, but not necessarily to release the source. Which license type should I have selected? This is the first time I have ever tried to publish any software on my own.

**Comment by shark92651** [comment]
Code is now posted in the master branch. Binaries are now under Releases

**Comment by tatarize** [comment]
Your license is blank, which is all rights reserved. Which is a fine license to use. Namely don't copy my code.

**Comment by shark92651** [comment]
Not sure how the license and my PDF were truncated when I pushed code, but those two files have been restored. Thanks for the heads up.
