### ISSUE TITLE
Missing Setup.exe

### ISSUE THREAD

**Issue by mer10t** [shark92651/LaserParamsConverter#4]
The actual ZIP folder doesn't include a .exe, please check the download part. Thank you.

**Comment by shark92651** [comment]
I think you are downloading the source and not the installer - the repository was rearranged a bit when I uploaded the source code. To find the installer, look on the right-hand side under "Releases" and download the LaserParamsConverter_1.0.6.zip to find the Windows installer.

**Comment by mer10t** [comment]
Ok got it. Thank you. I was following Alex's video and ended up with the source files.
