### ISSUE TITLE
Parse laser parameters from Ezcad2 files.

### ISSUE THREAD

**Issue by tatarize** [shark92651/LaserParamsConverter#9]
When you save an Ezcad2 file the 256 pens you're using at that point are saved within the file. It would be of some use to some people to parse this, especially for your program. I won't bother to do the more tedious work of parameter parsing if there's it's not something you'd care about. But, this should give you a solid roadmap of most of the format.

---

The file format is as follows.

### Header
* EZCADUNI written in 16-bit string.
* 0x0000 = 0
* 0x07D1 = 2001
* <Author String> this is 16-bit string padded out to 60 characters.
* <Date String> this is 16-bit string padded out to 60 characters.
* <Comment String> this is 16-bit string padded out to 60 characters.
* 140 bytes of 0x00 of unknown providence.

### Seek Table
* Absolute Seek Location of the start of the preview (4 bytes)
* 0x0000 4 bytes (Unknown)
* Start location of the Parameters <4 bytes>
* Start location of the Font block <4 bytes>.
* 0x0000 4 bytes (Unknown)
* Absolute seek location of vectors within the file.
    * If there are no vectors this value is 0x0000). (Strongly suspect the other 0x0000 are for other sections that are unknown)
* Absolute seek location of the start of unknown block of 400 0x00 values just before vectors, near the end.

### Unknown Table
* 96 Characters of unknown 0x00.

### Preview Table (Preview table can be fully omitted, if seek location is zeroed out)
* Width of preview (0x000000C8 = 200)
* Height of preview (0x000000C8 = 200)
* 0x00000320 = 800
* 0x00200001 (unknown)
* 0x00000000 (unknown).
* 200 x 200 bitmap of 4 byte RGB0 color (highest bit blanked rather than using 3 bits) = 4 * 200 * 200 = 160000 bytes.

### Font Table (Always exists, only 4 bytes if 0 fonts)
* 4 bytes of 0x00, if zero. If there's a font then we have additional 96 bytes per string value.
* For each, font listed 100 bytes of (maybe string data).

### Parameter Table
* Number of parameters. This should be 00 01 00 00 which is 0x100 or 256.
* Seek location of first parameter. This is often exactly at the same location as this is followed by the parameters.

#### Parameter Data.
* 3d 00 00 00 (Usually to start)
* These are like 0x17C in length and there's like 256 of them. Saving a blank file in Ezcad results in some parameter changing for each of the parameters.

#### Unknown block of 400 0x00
* 0x190 (400 bytes) of zeros.

#### Vector Data
If there are no vectors this data is omitted and the seek for the vector data is set to zero.
* Section of 7 length values (unknown)
* Section of much more dense characters (probably floats).

# Harvesting Settings.
* Seek to 0x160 read the value for the Parameter table.
* Absolute seek to parameter table.
* Read how many parameters we have (very likely 256).
* Read seek location of first parameter. (very likely current seek position)
* Absolute seek to parameters.
* Read n parameters.

**Comment by shark92651** [comment]
Thanks for this detailed research!

**Comment by tatarize** [comment]
I finished my parsing project to fully harvest all the data. The vector stuff gets pretty extensive and it's entirely a working format so parsing is basically 1:1 with the check boxes in the dialog etc. Though interesting enough you can extract the executed hatches as such, which is sort of interesting, and spirals are sort of the same way. Etc. 

See: https://github.com/meerk40t/meerk40t/blob/main/meerk40t/extra/ezd.py
